version: '2'
services:

  control-machine:
    ports:
      - 8888:8888/tcp
    image: chusiang/ansible-jupyter:alpine-3.6
  
  managed-node-ubuntu:
    ports:
      - 2221:22/tcp
    image: chusiang/ansible-managed-node:ubuntu-16.04
  
  managed-node-debian:
    ports:
      - 2222:22/tcp
    image: chusiang/ansible-managed-node:debian-9
  
  managed-node-centos:
    ports:
      - 2223:22/tcp
    image: chusiang/ansible-managed-node:centos-7

  managed-node-alpine:
    ports:
      - 2224:22/tcp
    image: chusiang/ansible-managed-node:alpine-3.6
  
