#!/usr/bin/env ansible-playbook
---

- hosts: localhost

  vars:
    some_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - git
      - openssl

    apk_packages: 
      - openssh-client
      - vim

    apt_packages: "{{ apk_packages }}"

    yum_packages:
      - openssh-clients
      - vim-minimal

    zypper_packages:
      - openssh
      - vim

    pip_packages:
      - docker-py
      - docker-compose
    
  tasks:
    - name: install some packages
      package: name={{ item }} state=latest
      with_nested: "{{ some_packages }}"
      when:
        - some_packages is defined

    - name: install apk packages
      apk: name={{ item }} state=latest
      with_nested: "{{ apk_packages }}"
      when:
        - apk_packages is defined
        - ansible_pkg_mgr == "apk"

    - name: install apt packages
      apt: name={{ item }} state=latest
      with_nested: "{{ apt_packages }}"
      when:
        - apt_packages is defined
        - ansible_pkg_mgr == "apt"

    - name: install yum packages
      yum: name={{ item }} state=latest
      with_nested: "{{ yum_packages }}"
      when:
        - yum_packages is defined
        - ansible_pkg_mgr == "yum"

    - name: install zypper packages
      zypper: name={{ item }} state=latest
      with_nested: "{{ zypper_packages }}"
      when:
        - zypper_packages is defined
        - ansible_pkg_mgr == "zypper"

    - name: install pip packages
      pip: name={{ item }} state=latest
      with_nested: "{{ pip_packages }}"
      when: pip_packages is defined

    - name: install the jupyter notebook
      pip: name=jupyter version=1.0.0 state=present 

# vim:ft=ansible :
