#!/usr/bin/env ansible-playbook
---

- hosts: localhost

  vars:
    # Same package on GNU/Linux.
    same_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - openssl

    # Alpine Linux.
    apk_packages: 
      - curl
      - git
      - openssh-client
      - vim

    # Debian, Ubuntu.
    apt_packages: "{{ apk_packages }}"

    # Arch Linux.
    pacman_packages:
      - curl
      - git
      - openssh
      - vim

    # Gentoo Linux.
    portage_packages:
      - net-misc/curl
      - dev-vcs/git
      - openssh
      - vim
      
    # CentOS.
    yum_packages:
      - curl
      - git
      - openssh-clients
      - vim-minimal

    # openSUSE
    zypper_packages: "{{ pacman_packages }}"

    # Python.
    pip_packages:
      - docker-py
      - docker-compose
    
  tasks:
    # General Linux.
    - name: install same packages
      package: name={{ item }} state=latest
      with_items: "{{ same_packages }}"
      when:
        - same_packages is defined

    # Alpine Linux.
    - name: install apk packages
      apk: name={{ item }} state=latest
      with_items: "{{ apk_packages }}"
      when:
        - apk_packages is defined
        - ansible_pkg_mgr == "apk"

    # Debian, Ubuntu.
    - name: install apt packages
      apt: name={{ item }} state=latest
      with_items: "{{ apt_packages }}"
      when:
        - apt_packages is defined
        - ansible_pkg_mgr == "apt"

    # Arch Linux.
    - name: install pacman packages
      pacman: name={{ item }} state=latest
      with_items: "{{ pacman_packages }}"
      when:
        - pacman_packages is defined
        - ansible_pkg_mgr == "pacman"

    # Gentoo Linux.
    - name: install portage packages
      portage: package={{ item }} state=present
      with_items:
       - "{{ portage_packages }}"
      when:
        - portage_packages is defined
        - ansible_pkg_mgr == "portage"

    # CentOS.
    - name: install yum packages
      yum: name={{ item }} state=latest
      with_items: "{{ yum_packages }}"
      when:
        - yum_packages is defined
        - ansible_pkg_mgr == "yum"

    # openSUSE
    - name: install zypper packages
      zypper: name={{ item }} state=latest
      with_items: "{{ zypper_packages }}"
      when:
        - zypper_packages is defined
        - ansible_pkg_mgr == "zypper"

    # General Python packages.
    - name: install some pip packages
      pip: name={{ item }} state=latest
      with_items: "{{ pip_packages }}"
      when: pip_packages is defined

    # Only install Jupyter.
    - name: install the jupyter notebook
      pip: name=jupyter version=1.0.0 state=present 

# vim:ft=ansible :
