#!/usr/bin/env ansible-playbook
---

- hosts: localhost

  vars:
    # Linux.
    some_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - git
      - openssl

    # Alpine.
    apk_packages: 
      - openssh-client
      - vim

    # Debian, Ubuntu.
    apt_packages: "{{ apk_packages }}"

    # Arch Linux.
    pacman_packages:
      - openssh
      - vim

    # CentOS.
    yum_packages:
      - openssh-clients
      - vim-minimal

    # openSUSE
    zypper_packages: "{{ pacman_packages }}"

    # Python.
    pip_packages:
      - docker-py
      - docker-compose
    
  tasks:
    # General Linux.
    - name: install some packages
      package: name={{ item }} state=latest
      with_nested: "{{ some_packages }}"
      when:
        - some_packages is defined

    # Alpine.
    - name: install apk packages
      apk: name={{ item }} state=latest
      with_nested: "{{ apk_packages }}"
      when:
        - apk_packages is defined
        - ansible_pkg_mgr == "apk"

    # Debian, Ubuntu.
    - name: install apt packages
      apt: name={{ item }} state=latest
      with_nested: "{{ apt_packages }}"
      when:
        - apt_packages is defined
        - ansible_pkg_mgr == "apt"

    # Arch Linux.
    - name: install pacman packages
      pacman: name={{ item }} state=latest
      with_nested: "{{ pacman_packages }}"
      when:
        - pacman_packages is defined
        - ansible_pkg_mgr == "pacman"

    # CentOS.
    - name: install yum packages
      yum: name={{ item }} state=latest
      with_nested: "{{ yum_packages }}"
      when:
        - yum_packages is defined
        - ansible_pkg_mgr == "yum"

    # openSUSE
    - name: install zypper packages
      zypper: name={{ item }} state=latest
      with_nested: "{{ zypper_packages }}"
      when:
        - zypper_packages is defined
        - ansible_pkg_mgr == "zypper"

    # General Python packages.
    - name: install some pip packages
      pip: name={{ item }} state=latest
      with_nested: "{{ pip_packages }}"
      when: pip_packages is defined

    # Only install Jupyter.
    - name: install the jupyter notebook
      pip: name=jupyter version=1.0.0 state=present 

# vim:ft=ansible :
